// Generated by https://quicktype.io

export interface Cantante {
    genres:string[];
    images:Image[];
    name:string;
    popularity:number;
    external_urls:External_urls;
    uri:string;
    type:string;
    id:string;
    href:string;
    followers: Followers;
}
export interface External_urls {
    spotify:string;
}
export interface Artista {
    artists: Artists;
}

export interface Artists {
    href:     string;
    items:    Item[];
    limit:    number;
    next:     null;
    offset:   number;
    previous: null;
    total:    number;
}

export interface Item {
    external_urls: ExternalUrls;
    followers:     Followers;
    genres:        string[];
    href:          string;
    id:            string;
    images:        Image[];
    name:          string;
    popularity:    number;
    type:          string;
    uri:           string;
}

export interface ExternalUrls {
    spotify: string;
}

export interface Followers {
    href:  null;
    total: number;
}

export interface Image {
    height: number;
    url:    string;
    width:  number;
}
